name: Generate Pokémon Contribution Map

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta todos los días a la medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate the contribution snake
    steps:
      # 1. Realiza el checkout del repositorio
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Genera el mapa y lo guarda automáticamente en la rama
      - name: Generate pokemon-contribution-map.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Andrey-Red2000
          outputs: |
            assets/pokemon-contribution-map.svg?palette=github-dark
          push_branch: main
